spring:
  profiles:
    active: dev
  # Uploading files
  servlet:
    multipart:
      enabled: true
      max-file-size: 128KB
      max-request-size: 128KB

---

spring:
  profiles: dev
  # RabbitMQ
  rabbitmq:
    username: root
    password: root
  # MySQL
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      location: /mnt/hdd/Projects/MOEA-Web-Framework/

guest:
  password: guest

jwt:
  token: "SkdIMUtCM3RaT3YmTW01cDk0QiM2QlVpXk4zdnY0NDk="

---

spring:
  profiles: prod
  # RabbitMQ
  rabbitmq:
    host: ${rabbitmq_host}
    port: ${rabbitmq_port}
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}
  #Redis
  redis:
    host: ${redis_host}
    port: ${redis_port}
  # MySQL
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
  datasource:
    initialization-mode: always
    url: jdbc:${mysql_url}
    username: ${mysql_username}
    password: ${mysql_password}

guest:
  password: ${guest_password}

jwt:
  token: ${jwt}