spring:
  profiles:
    active: dev
  # Uploading files
  servlet:
    multipart:
      enabled: true
      max-file-size: 128KB
      max-request-size: 128KB

---

spring:
  profiles: dev
  r2dbc:
    # R2DBC_URI: 'r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE'
    url: "r2dbc:postgresql://localhost/moeawebframework"
    username: "postgres"
    password: "postgres"
  main:
    lazy-initialization: true


logging.level.org.springframework.data.r2dbc: DEBUG

cdn_url: 'localhost:8070'
rsocket_url: 'localhost:7000'
authentication_issuers: "http://localhost:8180/auth/realms/MOEA-Web-Framework"

---

spring:
  profiles: prod
  main:
    lazy-initialization: true

cdn_url: ${CDN_URL}
rsocket_url: ${RSOCKET_URL}