spring:
  profiles:
    active: dev
  # Uploading files
  servlet:
    multipart:
      enabled: true
      max-file-size: 128KB
      max-request-size: 128KB

---

spring:
  profiles: dev

logging.level.org.springframework.data.r2dbc: DEBUG

CDN_URI: 'localhost:8070'
R2DBC_URI: 'r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE'
RSOCKET_HOST: 'localhost'
RSOCKET_PORT: 7000

---

spring:
  profiles: prod
  #Redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

CDN_URI: ${CDN_URI}
R2DBC_URI: ${R2DBC_URI}
RSOCKET_HOST: ${RSOCKET_HOST}
RSOCKET_PORT: ${RSOCKET_PORT}