spring:
  profiles:
    active: dev
  main:
    lazy-initialization: true

---

spring:
  profiles: dev
  r2dbc:
    url: "r2dbc:postgresql://localhost/moeawebframework"
    username: "postgres"
    password: "postgres"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8180/auth/realms/MOEA-Web-Framework"

logging.level.org.springframework.data.r2dbc: DEBUG

rsocket_url: "localhost:7000"

---

spring:
  profiles: prod

rsocket_url: ${RSOCKET_URL}
