spring:
  profiles:
    active: dev
  main:
    lazy-initialization: true
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
      file-size-threshold: 500KB

---

spring:
  r2dbc:
    url: "r2dbc:mysql://localhost/moeawebframework"
    username: "root"
    password: "root"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8180/auth/realms/MOEA-Web-Framework"
  config:
    activate:
      on-profile: dev

logging.level.org.springframework.data.r2dbc: DEBUG

rsocket_url: "localhost:7000"

---

spring:
  config:
    activate:
      on-profile: prod
