spring:
  profiles:
    active: dev
  # Uploading files
  servlet:
    multipart:
      enabled: true
      max-file-size: 128KB
      max-request-size: 128KB

---

spring:
  profiles: dev
  # RabbitMQ
  rabbitmq:
    username: root
    password: root
  #Redis
  redis:
    host: localhost
    port: 6379
  # MySQL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      location: /mnt/hdd/Projects/MOEA-Web-Framework/

admin:
  password: admin

jwt:
  token: "SkdIMUtCM3RaT3YmTW01cDk0QiM2QlVpXk4zdnY0NDk="

---

spring:
  profiles: prod
  # RabbitMQ
  rabbitmq:
    username: root
    password: ${admin_pass}
  #Redis
  redis:
    host: localhost
  # MySQL
#  datasource:
#    initialization-mode: always
#    url: jdbc:mysql://localhost/users
#    username: root
#    password: ${admin_pass}

admin:
  password: ${admin_pass}

jwt:
  token: ${jwt}