@backend = http://localhost:8080/queue

### Add problem

POST {{backend}}/addProblemSolver HTTP/1.1
Content-Type: application/json

{
  "name": "Asd",
  "problem": "Belegundu",
  "algorithm": "CMA-ES",
  "numberOfEvaluations": 500,
  "numberOfSeeds": 10
}

@rabbitId = e15aebd2-06eb-42f7-89e5-9ad4e913ab18

### Solve problem

GET {{backend}}/solveProblemSolver/{{rabbitId}} HTTP/1.1
Content-Type: application/json

### Cancel problem

GET {{backend}}/cancelProblemSolver/{{rabbitId}} HTTP/1.1
Content-Type: application/json