@backend = http://localhost:8080/queue

### Add problem

POST {{backend}}/addQueueItem HTTP/1.1
Content-Type: application/json

{
  "name": "Asd",
  "problem": "Belegundu",
  "algorithm": "CMA-ES",
  "numberOfEvaluations": 500,
  "numberOfSeeds": 10
}

@rabbitId = 37c77cb0-fe5a-463e-93a0-a251f691b755

### Solve problem

GET {{backend}}/solveQueueItem/{{rabbitId}} HTTP/1.1
Content-Type: application/json

### Cancel problem

GET {{backend}}/cancelQueueItem/{{rabbitId}} HTTP/1.1
Content-Type: application/json