@backend = http://localhost:8080/queue

POST {{backend}}/addProblem HTTP/1.1
Content-Type: application/json

{
  "name": "Belegundu",
  "algorithm": "CMA-ES",
  "numberOfEvaluations": "10000",
  "numberOfSeeds": "10"
}

###

GET {{backend}}/solveProblem/4583775679180042248 HTTP/1.1

###
GET {{backend}}/cancelProblem/4583775679180042248 HTTP/1.1

###
# Login
POST http://localhost:8080/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=user&password=password