@backend = http://localhost:8080
@userRoute = {{backend}}/user

### Register user

POST {{userRoute}}/register HTTP/1.1
Content-Type: application/json

{
  "username": "user",
  "password": "user",
  "email": "user@email.com",
  "firstName": "User"
}

### Login user

POST {{userRoute}}/login HTTP/1.1
Content-Type: application/json

{
  "username": "user",
  "password": "user"
}

@jwt = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNTg2MDk3MDUyLCJleHAiOjE1ODYxMzMwNTJ9.9-AV3PZhDO4XpXqztS6xCF4AU-4-NyJnoAiOynhA24k

### Add queue item

POST {{userRoute}}/queue/addQueueItem HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Problemad noua",
  "problem": "Belegundu",
  "algorithm": "CMA-ES",
  "numberOfEvaluations": "10000",
  "numberOfSeeds": "10"
}

@rabbitId = 447b7a10-6fec-499e-91e8-4a10948d7895

### Solve queue item

GET {{userRoute}}/queue/solveQueueItem/{{rabbitId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{

}

### Cancel problem

GET {{userRoute}}/queue/cancelQueueItem/{{rabbitId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}