version: "3"
services:
  problems:
    image: redis:alpine
    ports:
      - "6379:6379"
  users:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users
    ports:
      - "3306:3306"
  results:
    image: reydw/moeawebframework_results
    hostname: moeawebframework
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
      - "15674:15674"
