version: "3"
services:
  sessions:
    image: redis:alpine
    ports:
      - "6379:6379"
  problems:
    image: redis:alpine
    ports:
      - "6378:6379"
  users:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users
    ports:
      - "3306:3306"
