openapi: 3.0.3
info:
  title: MOEA Web Framework
  description: A web platform for the MOEA Framework
  version: 3.0.1
tags:
  - name: Algorithms
    description: Operations for algorithms
  - name: Problems
    description: Operations for problems
  - name: Reference sets
    description: Operations for reference sets
  - name: Evaluations
    description: Operations for evaluations
  - name: Standards
    description: Operations for standard algorithms, problems and reference sets
servers:
  - url: "http://localhost:8080"
paths:
  /algorithms:
    $ref: "./paths/algorithms.yml"
  /algorithms/{id}/download:
    $ref: "./paths/algorithm_download.yml"
  /algorithms/{id}:
    $ref: "./paths/algorithm.yml"

  /problems:
    $ref: "./paths/problems.yml"
  /problems/{id}/download:
    $ref: "./paths/problem_download.yml"
  /problems/{id}:
    $ref: "./paths/problem.yml"

  /referenceSets:
    $ref: "./paths/referenceSets.yml"
  /referenceSets/{id}/download:
    $ref: "./paths/referenceSet_download.yml"
  /referenceSets/{id}:
    $ref: "./paths/referenceSet.yml"

  /evaluations:
    $ref: "./paths/evaluations.yml"
  /evaluations/{id}:
    $ref: "./paths/evaluation.yml"

  /standards/algorithms:
    $ref: "./paths/standardAlgorithms.yml"
  /standards/problems:
    $ref: "./paths/standardProblems.yml"
  /standards/referenceSets:
    $ref: "./paths/standardReferenceSets.yml"

components:
  schemas:
    NewCommonStructure:
      $ref: "./schemas/NewCommonStructure.yml"
    CommonStructure:
      $ref: "./schemas/CommonStructure.yml"
    NewEvaluation:
      $ref: "./schemas/NewEvaluation.yml"
    Evaluation:
      $ref: "./schemas/Evaluation.yml"
    CommonIndicator:
      $ref: "./schemas/CommonIndicator.yml"
    QualityIndicators:
      $ref: "./schemas/QualityIndicators.yml"
    StandardCommonStructure:
      $ref: "./schemas/StandardCommonStructure.yml"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
