openapi: 3.0.3
info:
  title: MOEA Web Framework
  description: A web platform for the MOEA Framework
  version: 3.0.2
tags:
  - name: Common structures
    description: Operations for common structures
  - name: Evaluations
    description: Operations for evaluations
  - name: Standards
    description: Operations for standard algorithms, problems and reference sets
servers:
  - url: "http://localhost:8080"
paths:
  /commonctructures:
    $ref: "./paths/commonStructures.yml"
  /commonstructures/{commonStructure}/{id}:
    $ref: "./paths/commonStructure.yml"
  /commonctructures/{commonStructure}/{id}/download:
    $ref: "./paths/commonStructure_download.yml"

  /evaluations:
    $ref: "./paths/evaluations.yml"
  /evaluations/{id}:
    $ref: "./paths/evaluation.yml"

  /standards/{commonStructure}:
    $ref: "./paths/standardCommonStructures.yml"

components:
  schemas:
    ID:
      $ref: "./schemas/ID.yml"
    NewCommonStructure:
      $ref: "./schemas/NewCommonStructure.yml"
    CommonStructure:
      $ref: "./schemas/CommonStructure.yml"
    ArrayCommonStructure:
      $ref: "./schemas/ArrayCommonStructure.yml"
    NewEvaluation:
      $ref: "./schemas/NewEvaluation.yml"
    Evaluation:
      $ref: "./schemas/Evaluation.yml"
    CommonIndicator:
      $ref: "./schemas/CommonIndicator.yml"
    QualityIndicators:
      $ref: "./schemas/QualityIndicators.yml"
    StandardCommonStructure:
      $ref: "./schemas/StandardCommonStructure.yml"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
